// Generated by CoffeeScript 1.10.0
var jrequest, request;

request = require('request');

jrequest = function(settings, success) {
  var req;
  req = request(settings, function(err, response, data) {
    if (!err && response.statusCode === 200) {
      return req._done(data);
    } else if (!err) {
      return req._fail(response, data);
    }
  }).on('error', function(err) {
    return req._fail(err);
  });
  req.done = function(cb) {
    req._done = cb;
    return req;
  };
  req.fail = function(cb) {
    req._fail = cb;
    return req;
  };
  return req;
};

module.exports = jrequest;

//# sourceMappingURL=index.js.map
