// Generated by CoffeeScript 1.10.0
var request;

request = require('jrequest');

request.get({
  url: 'http://www.google.com'
}).done(function(data) {
  return console.log(data);
}).fail(function(err, data) {
  return console.log("Error", err.statusCode, data);
}).always(function(data) {
  return console.log("Always", data);
});

//# sourceMappingURL=test.js.map
