// Generated by CoffeeScript 1.10.0
var request;

request = require('jrequest.js');

request.get({
  url: 'http://google.com'
}).done(function(data) {
  return console.log(data);
}).fail(function(err) {
  return console.log("Error", err.statusCode);
});

//# sourceMappingURL=test.js.map
